### ISSUE TITLE
FR: Sortierung nach Farbe

### ISSUE THREAD

**Issue by zonky2** [MetaModels/attribute_color#6]
z.B. https://gist.github.com/alexkingorg/2158428

für https://github.com/MetaModels/core/issues/851

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@zonky2 could you please have a final look at this and tell if your issue has been resolved?

**Comment by zonky2** [comment]
Add Sorting options asc and desc
PR #8

**Comment by zonky2** [comment]
Fixed with https://github.com/MetaModels/attribute_color/commit/b0f245ea870ea3b883b0fc4850821fc60e2fdaf8
